apiVersion: v1
kind: Service
metadata:
  name: nginix-service
  labels:
    run: my-nginx
spec:
  type: NodePort      
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: nginx485
